### PR TITLE
Feature/factory additional/override helpers

### PR DESCRIPTION
**Pull request by jakejohns**
How do people feel about the ability to pass additional/override helpers?

For example:

```php

$my_helpers = [
    'foo' => $di->lazyNew(MyFooHelper::class),
    'url' => $di->lazyGetCall('radar/adr:router', 'newUrlHelper')
];

$Helper_locator_factory->newInstance($my_helpers);

```

### CODE REVIEW

**Comment by harikt** [comment]
@jakejohns not against passing helpers to factories.

**Comment by harikt** [comment]
Seems conflicts . Does this PR also contains things from recently merged PR https://github.com/auraphp/Aura.Html/pull/54 .

**Comment by jakejohns** [comment]
I rebased this branch. It should be happy now.

**Comment by harikt** [comment]
I am :+1:  for this. Lets merge it.

**Comment by jakejohns** [comment]
@harikt if you like it, and @pmjones has no objection, I guess do it !

**Pull request merged**
