### PR TITLE
Add Void Helper

### PR DESCRIPTION
**Pull request by jakejohns**
Add helper for use with "[void](https://www.w3.org/TR/html5/syntax.html#void-elements)" 'self closing' tags, eg:
- area, 
- base, 
- br, 
- col, 
- embed, 
- hr, 
- keygen, 
- param, 
- source,
- track
- wbr

### CODE REVIEW

**Comment by harikt** [comment]
Thank you. 

I wasn't aware of some of them :).

**Comment by jakejohns** [comment]
I think this one is safe to merge without further discussion. I'll wait a bit for objections, and merge shortly.

**Comment by harikt** [comment]
sure :+1: .

**Comment by jakejohns** [comment]
ok, first merge. that was terrifying. hope i did that right :-/

**Comment by harikt** [comment]
Nothing is right or wrong. Everyone makes mistake that is why we are using git ;) . We can always revert if we need it :-) .

And congrats for the first merge :+1:  .

**Pull request merged**
