### PR TITLE
Add Element Helper

### PR DESCRIPTION
**Pull request by jakejohns**
> - Add helper to generate a complete HTML element (open tag, content, close tag)
> - Also add tests

I often find myself doing something like this:

``` php
// [...]
foreach ($data as $val) {
    echo $this->tag($val['tag'], $val['attr'])
        . $val['content']
        . $this->tag('/' . $val['tag']);
}
```

I thought it might be useful to just be able to do this:

``` php
// [...]
foreach ($data as $val) {
    echo $this->ele($val['tag'], $val['content'], $val['attr']);
}
```

Thoughts? Useful? Too redundant?

### CODE REVIEW

**Comment by pmjones** [comment]
Looks nice. My only comment is on the name. Do we want `Element`, or would `Html`, `Content`, or something else be more appropriate?

**Comment by pmjones** [comment]
And there'd likely need to be a `Raw` version of it as well, where the content does not get escaped.

**Comment by pmjones** [comment]
Finally, do we want to put $attr before $content, to reflect the order in which the output occurs? (I.e., the attributes will be shown earlier than the content will.)

**Comment by jakejohns** [comment]
### Name

I went with `Element` as I felt like that was the most appropriate here.
In general, I feel like the commonly used parlance would be something like:
- **Tag**: open or close tag itself
- **Content**: the content _inside_ open and close tags
- **Html**: the language itself, or the full doc, or a longer snippet (also, as
  it's the name of the package, i find it a little confusing)

Here's some random examples: [[1]](http://www.456bereastreet.com/archive/200508/html_tags_vs_elements_vs_attributes/) [[2]](http://stackoverflow.com/questions/8937384/what-is-the-difference-between-tags-and-elements-html) [[3]](https://en.wikipedia.org/wiki/HTML_element)

### Raw

Raw helper should be here in this PR https://github.com/jakejohns/Aura.Html/blob/feature/element/src/Helper/ElementRaw.php

### Order

My thinking on order of parameters was to avoid passing a null in the middle of
the call for elements which have no attributes. eg:

``` php
// for <h1>title</h1>
echo $this->ele('h1', 'title');
// vs
echo $this->ele('h1', null, 'title');
```

### Further (Structure Helper)

I started thinking about building in a 'recursive functionality' to deal with
more complex structures, but held off here as theres some separate
considerations in regards to raw vs escaped. I'll open a different PR ( #41 )but I was
thinking of a way to do something like this:

``` php
// output <h1 class="asd"><a href="/href"><span class="baz">Title</span></a></h1>
$struct = [
    'h1',
    [
        'a',
        [
            'span',
            'Title',
            ['class' => 'baz']
        ],
        ['href' => '/href']
    ],
    [
        'class' => 'asd'
    ]
];

echo $this->struct($struct);
```

The idea being that if `$content` is an `array` it calls the (raw) helper.

The extra consideration here being that both the 'raw' and 'escaped' version of
a 'structure' helper would need to be able to call the raw version for each
step in which `$content` is not a `string`. The difference between 'raw' and
`escaped` here would be whether or not it escapes the final nested string.

I think this would mean doing something like this: #41

Which uses a base `AbstractElementHelper` to consolidate the redundant code.

Thoughts?

**Comment by jakejohns** [comment]
@pmjones I'm sure you're busy, but any further thoughts here?

**Comment by jakejohns** [comment]
Anyone have any other thoughts here?

**Comment by jakejohns** [comment]
@harikt or @pmjones : Does anyone have strong feelings on the question of "order" here? 
If so, I'll switch it.
If not, I think ill merge this as it is. If one wants the order "attr, content", they can use the existing tag helper, but if one is using this element helper then presumably the "content" is less likely to be null?

**Comment by pmjones** [comment]
I think the order is fine; the other helpers (looking at them now) generally have $attr after the "main" value.

**Comment by harikt** [comment]
I am :+1: . 

Thank you.

**Pull request merged**
