### PR TITLE
Input helper needs to be injected.

### PR DESCRIPTION
**Pull request by harikt**

### CODE REVIEW

**Comment by harikt** [comment]
@pmjones I am merging this, if you have any issues please revert.

**Comment by harikt** [comment]
@koriym do you have any thoughts on the configuration for the Aura.Di for input ?

See https://gist.github.com/harikt/8551536#file-aura-html-view-di-php-L12 .

**Comment by koriym** [comment]
Hi @harikt 
It seems pretty straightforward. :+1:

**Comment by harikt** [comment]
@koriym you missed what I was looking for. I need to convert that to a dependency injection stuff.

**Pull request merged**
