### PR TITLE
Return empty string instead of null in AbstractList::__toString

### PR DESCRIPTION
**Pull request by Avaq**
In PHP, `__toString` _must_ return a string, or an error is raised.

### CODE REVIEW

**Comment by harikt** [comment]
The build fails, I assume it can be returned null than empty string will help.

**Comment by harikt** [comment]
@Avaq see https://travis-ci.org/auraphp/Aura.Html/jobs/38716823#L41

**Comment by Avaq** [comment]
Ah there is a unit-test testing for specifically `null`. Very odd because when `null` is returned from `__toString` on my PHP version, I get:

> Catchable fatal error: Method Aura\Html\Helper\Ul::__toString() must return a string value in ...

**Comment by Avaq** [comment]
Shall I modify the unit-test or is this intended behaviour?

**Comment by harikt** [comment]
You should ping @pmjones then.

_Hari K T_

You can ring me : +91 9388 75 8821

http://harikt.com , https://github.com/auraphp ,
http://www.linkedin.com/in/harikt , http://www.xing.com/profile/Hari_KT

Skype  : kthari85
Twitter : harikt

**Comment by Avaq** [comment]
The problem is as follows: When PHP uses the `__toString()` method to cast an object into a string, it forces the method to return a `string`, as demonstrated by [this test](http://3v4l.org/dd7hD). The unit-tests never test for this, because they always call `$ol()->__toString()` directly.

I will modify the unit-test accordingly and push to this branch.

**Comment by harikt** [comment]
@Avaq may be branch out from this and send a different PR .

**Comment by harikt** [comment]
I am ok with this. Assuming no one tried to compare the return of `__toString` to null as in unit tests ;-) .

**Comment by Avaq** [comment]
People who expect the return value of `__toString` to equal `null` are asking for their code to break anyway. :smiling_imp:

**Comment by Avaq** [comment]
:white_check_mark:

**Pull request merged**
