### PR TITLE
Add nested HTML snippet/structure helper

### PR DESCRIPTION
**Pull request by jakejohns**
This is what I mentioned in #40 about being able to pass a nested array to generate more complex nested HTML structures.

``` php
// output <h1 class="asd"><a href="/href"><span class="baz">Title</span></a></h1>
$struct = [
    'h1',
    [
        'a',
        [
            'span',
            'Title',
            ['class' => 'baz']
        ],
        ['href' => '/href']
    ],
    ['class' => 'asd']
];

echo $this->struct($struct);
```

Thoughts?

### CODE REVIEW

**Comment by jakejohns** [comment]
@pmjones I'm sure you're busy, but any thoughts here?

**Comment by harikt** [comment]
I guess this contains the necessary files of #40 also right ?

**Comment by jakejohns** [comment]
Yes. This has the "Element" helper as well. However, the 2nd commit here restructures it a bit to put the common code into a single place.

**Comment by jakejohns** [comment]
Anyone have any other thoughts here?

**Comment by harikt** [comment]
not really.

**Pull request merged**
