### PR TITLE
Label Helper

### PR DESCRIPTION
**Pull request by jelofson**
Added a new label helper + tests

### CODE REVIEW

**Comment by harikt** [comment]
Thanks. I thought it was merged.
I leave this for the approval of @pmjones

**Comment by jelofson** [comment]
No prob. This is a new one. 

Incidentally, I did try using the new label helper within the checkbox helper and it worked fine. My only reservation was the amount of work involved to get access to another helper. You have to pass the locator to the closure in the registration array. I am not yet sure if the juice is worth the squeeze. If this gets accepted, I can submit another showing the checkbox helper using the label helper. 

I still want to give Aura.Html an extensive workout trying it in various scenarios. It looks great thus far. 

Jon

**Comment by harikt** [comment]
@pmjones this is good for merge. Your thoughts ?

**Comment by pmjones** [comment]
merged -- thanks!

**Pull request closed without merging**
