### PR TITLE
Convert left over 5.4 closing bracket

### PR DESCRIPTION
**Pull request by dmolineus**
Closing bracked of array was not converted to 5.3 style

### CODE REVIEW

**Comment by harikt** [comment]
Thank you @netzmacht  for the first path, and welcome to the world of aura.

**Comment by harikt** [comment]
What is your twitter handle? Just to send a tweet about thanks for the first PR.

**Comment by dmolineus** [comment]
@harikt I'm not user twitter anymore.

**Comment by harikt** [comment]
ok. no pblm.
Thanks

**Pull request merged**
